services:
  - type: web
    name: eccos-girl-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    healthCheckPath: /health

    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        value: "1531068742631555337"
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_GUILD_ID
        value: "1468916727940382786"
      - key: PORT
        value: "3000"
      - key: SESSION_SECRET
        generateValue: true
      - key: REDIRECT_URI
        value: "https://eccos-girl-bot.onrender.com/auth/discord/callback"
      - key: SITE_PASSWORD
        value: "eccosgirl"

